name: dbt_test_repo


sources:
  dbt_test_schema:  # Schema containing the source tables
    database: dbt_test_db  # Snowflake database name
    schema: dbt_test_schema  
    tables:
      fact_sales:  # Reference fact table

models:
  dbt_test_repo:
    test_dbt_model:
      materialized: table  # Ensures table creation
