
dbt_test_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: JJIVGWT-CJ95375
      user: ANKYZ
      password: Axelblaz@0075295         # make sure there are no extra spaces
      role: ACCOUNTADMIN
      database: DBT_TEST_DB
      warehouse: COMPUTE_WH
      schema: DBT_TEST_SCHEMA
      threads: 1
      client_session_keep_alive: false

